# Inserts a blank line between shell prompts
# add_newline = false
command_timeout = 1000

# Replace the "â¯" symbol in the prompt with "âœ"
# [character]                            # The name of the module we are configuring is "character"
# success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"

# # Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

# [git_branch]
# symbol = "ğŸŒ± "

# Some Nerd font is required to see all the characters
# and glyphs properly: https://starship.rs/guide/#prerequisites

# https://en.wikipedia.org/wiki/Box-drawing_character
# https://en.wikipedia.org/wiki/Arrow_(symbol)
